### ISSUE TITLE
Zoomed in cameras cause the ui to become misplaced and incorrectly scaled

### ISSUE THREAD

**Issue by CreggEgg** [bytestring-net/bevy_lunex#44]
When changing the zoom of a camera with the projection.scale property the ui is not affected and ends up improperly scaled and positioned

**Comment by IDEDARY** [comment]
Fixed in version `0.1.1` for `Bevy 0.14.0`. I will release the crate once `0.14.0` lands. For now you can use the `"dev"` branch (0.14.0) on GitHub.
